### ISSUE TITLE
Add ability to edit own comments

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/wordcloud-app#13]
Would be nice for users to be able to review and edit the comments they've submitted.  

- edit comment text
- add / edit tags attached to the comment

**How:** 
- Generate comment IDs locally to store them in local cache
- update newComment <firebase-document> to push key instead of letting firebase generate the keys.

- there is a page that currently shows a full list of comments. This can be edited to show only your own comments (with the locally created IDs)

**Comment by chrismclarke** [comment]
Implemented, commits 42aecb200dbcc809d5b22c55cbe5109eab15a843 bdebda76ffbe074ae23314cfc30d50e620545741
App now defines the comment pushID itself instead of autogen (using same algorithm as polymer anyway). Add comment function uses this pushID when saving the doc and binds to it so any changes update that key in the database. Currently limited to just one comment per user but could be saved locally to allow multiple responses for the question and/or across multiple questions.
